services:
  postgres:
    image: postgres
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped

  #Adding testing database for integration tests
  postgres-test:
    image: postgres
    container_name: my_postgres_test
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdatabase
    volumes:
      - pgdata-test:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - backend
    depends_on:
      - postgres
    restart: unless-stopped

  app:
    build: .
    container_name: remitly_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - postgres
    restart: unless-stopped

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    container_name: remitly_test
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-test:5432/testdatabase
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpassword
      SPRING_PROFILES_ACTIVE: test
    networks:
      - backend
    depends_on:
      - postgres-test

volumes:
  pgdata:
  pgdata-test:
  pgadmin:

networks:
  backend:
    driver: bridge