spring:
  application:
    name: RemitlyInternship

  datasource:
    url: jdbc:postgresql://postgres:5432/mydatabase
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update #create-drop ==> each time new database
    show-sql: true
    open-in-view: false
